In [114]:
import numpy as np

from numpy.linalg import inv, eig, svd
np.set_printoptions(precision=6, suppress=True)

A = np.array([
    [4, -2, 2, 1],
    [1,  1, 0, 1],
    [-2, 1, 3, -1],
    [1,  3, -1, 2]
], dtype = float)

In [115]:
# 1. Inverse of A

A_inv = inv(A)
print("Inverse of A:\n",A_inv)

Inverse of A:
 [[  5. -30.   1.  13.]
 [  4. -25.   1.  11.]
 [ -1.   7.   0.  -3.]
 [ -9.  56.  -2. -24.]]


In [116]:
# 2. Eigenvalues and Eigenvectors

eigenvalues, eigenvectors = eig(A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (columns):\n", eigenvectors)


Eigenvalues:
 [-0.022317+0.j        3.610453+1.720341j  3.610453-1.720341j
  2.801411+0.j      ]

Eigenvectors (columns):
 [[-0.436762+0.j        0.575983+0.j        0.575983-0.j
   0.267489+0.j      ]
 [-0.369001+0.j        0.009623-0.210522j  0.009623+0.210522j
  -0.348939+0.j      ]
 [ 0.102397+0.j       -0.008217+0.551423j -0.008217-0.551423j
  -0.061208+0.j      ]
 [ 0.813998+0.j       -0.188691-0.533004j -0.188691+0.533004j
  -0.896072+0.j      ]]


In [117]:
# 3. Diagonalization

P = eigenvectors
D = np.diag(eigenvalues)
P_inv = inv(P)

print("P = ",P)
print("\nD = ",D)

# Verify A = P D P⁻¹
A_diagonalized = P @ D @ P_inv
print("\nDiagonalized A (P D P⁻¹):\n", A_diagonalized)


P =  [[-0.436762+0.j        0.575983+0.j        0.575983-0.j
   0.267489+0.j      ]
 [-0.369001+0.j        0.009623-0.210522j  0.009623+0.210522j
  -0.348939+0.j      ]
 [ 0.102397+0.j       -0.008217+0.551423j -0.008217-0.551423j
  -0.061208+0.j      ]
 [ 0.813998+0.j       -0.188691-0.533004j -0.188691+0.533004j
  -0.896072+0.j      ]]

D =  [[-0.022317+0.j        0.      +0.j        0.      +0.j
   0.      +0.j      ]
 [ 0.      +0.j        3.610453+1.720341j  0.      +0.j
   0.      +0.j      ]
 [ 0.      +0.j        0.      +0.j        3.610453-1.720341j
   0.      +0.j      ]
 [ 0.      +0.j        0.      +0.j        0.      +0.j
   2.801411+0.j      ]]

Diagonalized A (P D P⁻¹):
 [[ 4.-0.j -2.+0.j  2.+0.j  1.-0.j]
 [ 1.+0.j  1.-0.j -0.+0.j  1.-0.j]
 [-2.-0.j  1.+0.j  3.-0.j -1.-0.j]
 [ 1.-0.j  3.-0.j -1.-0.j  2.-0.j]]


In [118]:
# Check if A_diagonalized ≈ A

is_identical = np.allclose(A, A_diagonalized)
print("\nIs A_diagonalized identical to A?", is_identical)


Is A_diagonalized identical to A? True


# 4. Explanation

Diagonalization is important because it simplifies matrix operations.
When a matrix A can be written as A = P D P⁻¹, where D is diagonal:
- Powers of A become easy: Aⁿ = P Dⁿ P⁻¹
- It reveals the matrix's structure via eigenvalues
- It enables efficient computation in systems of differential equations, quantum mechanics, and PCA



In [119]:
# 5. SVD Reconstruction

U, S, Vt = svd(A)

In [120]:
# Choose a threshold to keep significant singular values

U, S, Vt = np.linalg.svd(A)

for k in range(1, 5):
    Sigma_k = np.zeros((U.shape[0], Vt.shape[0]))
    Sigma_k[:k, :k] = np.diag(S[:k])
    
    A_R_k = U @ Sigma_k @ Vt
    
    print(f"\nRank {k} Reconstruction")
    print(f"Singular values used: {S[:k]}")
    print("Reconstructed A_R_k:\n", np.round(A_R_k, 2)) 
    print("Is reconstructed A for sigma =",sigma_threshold ,"≈ original A? ", np.allclose(A, A_R_k, atol=1e-2))


Rank 1 Reconstruction
Singular values used: [5.254937]
Reconstructed A_R_k:
 [[ 4.16 -1.68  0.49  1.42]
 [ 0.72 -0.29  0.08  0.25]
 [-1.85  0.75 -0.22 -0.63]
 [ 0.27 -0.11  0.03  0.09]]
Is reconstructed A for sigma = 1 ≈ original A?  False

Rank 2 Reconstruction
Singular values used: [5.254937 4.481288]
Reconstructed A_R_k:
 [[ 3.93 -2.53  1.3   0.82]
 [ 0.94  0.5  -0.68  0.81]
 [-2.19 -0.51  0.99 -1.53]
 [ 0.89  2.14 -2.14  1.7 ]]
Is reconstructed A for sigma = 1 ≈ original A?  False

Rank 3 Reconstruction
Singular values used: [5.254937 4.481288 3.209909]
Reconstructed A_R_k:
 [[ 4.   -2.    2.    1.  ]
 [ 1.01  1.   -0.    0.99]
 [-2.    1.    3.   -1.  ]
 [ 1.    3.   -1.    2.  ]]
Is reconstructed A for sigma = 1 ≈ original A?  True

Rank 4 Reconstruction
Singular values used: [5.254937 4.481288 3.209909 0.013229]
Reconstructed A_R_k:
 [[ 4. -2.  2.  1.]
 [ 1.  1. -0.  1.]
 [-2.  1.  3. -1.]
 [ 1.  3. -1.  2.]]
Is reconstructed A for sigma = 1 ≈ original A?  True
